/**
 * Supabase Client Configuration
 * Provides both public and admin clients for different use cases
 */

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

/**
 * Public Supabase Client
 * Use this for frontend operations and public queries
 * Row Level Security (RLS) is enforced
 */
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Admin Supabase Client (Server-side only!)
 * Use this for admin operations, bypasses RLS
 * ONLY use in API routes, server components, or cron jobs
 * NEVER expose to frontend/client code
 */
export const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
});

/**
 * Database Types (will be auto-generated by Supabase later)
 */
export type Profile = {
  id: string;
  first_name: string;
  last_initial: string;
  city: string;
  state: string;
  zip_code: string;
  professional_summary: string;
  office: string;
  profession_type: string;
  skills: string[] | null;
  created_at: string;
  updated_at: string;
  source_file: string | null;
  is_active: boolean;
};
